# Generated by Django 4.2.27 on 2026-01-10 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoGravimetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estacao', models.CharField(help_text='Nome identificador da estação gravimétrica', max_length=200, verbose_name='Nome da Estação')),
                ('codigo_estacao', models.CharField(help_text='Código único da estação', max_length=50, unique=True, verbose_name='Código da Estação')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude em graus decimais', max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude (graus)')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude em graus decimais', max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude (graus)')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude em metros acima do nível do mar', max_digits=8, null=True, verbose_name='Altitude (m)')),
                ('valor_gravidade', models.DecimalField(decimal_places=5, help_text='Valor da gravidade em miligals', max_digits=10, verbose_name='Valor da Gravidade (mGal)')),
                ('incerteza', models.DecimalField(blank=True, decimal_places=5, help_text='Incerteza da medição em miligals', max_digits=8, null=True, verbose_name='Incerteza (mGal)')),
                ('data_medicao', models.DateField(help_text='Data em que a medição foi realizada', verbose_name='Data da Medição')),
                ('operador', models.CharField(blank=True, help_text='Nome do operador responsável pela medição', max_length=100, null=True, verbose_name='Operador')),
                ('instrumento', models.CharField(blank=True, help_text='Modelo do gravímetro utilizado', max_length=100, null=True, verbose_name='Instrumento')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre a medição', null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se a medição está ativa no sistema', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Medição Gravimétrica',
                'verbose_name_plural': 'Medições Gravimétricas',
                'ordering': ['-data_medicao', 'nome_estacao'],
                'indexes': [models.Index(fields=['codigo_estacao'], name='medicoes_me_codigo__657d76_idx'), models.Index(fields=['data_medicao'], name='medicoes_me_data_me_178b2a_idx')],
            },
        ),
    ]
