# Generated by Django 4.2.27 on 2026-01-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaogravimetrica',
            name='anomalia_bouguer',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Anomalia de Bouguer em miligals (pode ser calculada automaticamente)', max_digits=10, null=True, verbose_name='Anomalia de Bouguer (mGal)'),
        ),
        migrations.AddField(
            model_name='medicaogravimetrica',
            name='densidade_referencia',
            field=models.DecimalField(blank=True, decimal_places=3, default=2.67, help_text='Densidade utilizada no cálculo da anomalia de Bouguer (padrão: 2.67 g/cm³)', max_digits=6, null=True, verbose_name='Densidade de Referência (g/cm³)'),
        ),
    ]
