# Generated by Django 4.2.27 on 2026-01-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0002_medicaogravimetrica_anomalia_bouguer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='densidade_referencia',
            field=models.DecimalField(decimal_places=3, default=2.67, help_text='Densidade utilizada no cálculo da anomalia de Bouguer (padrão: 2.67 g/cm³)', max_digits=6, verbose_name='Densidade de Referência (g/cm³)'),
        ),
    ]
