# Generated by Django 4.2.27 on 2026-01-10 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0003_alter_medicaogravimetrica_densidade_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='anomalia_bouguer',
            field=models.DecimalField(blank=True, decimal_places=5, help_text='Anomalia de Bouguer em miligals (calculada automaticamente)', max_digits=12, null=True, verbose_name='Anomalia de Bouguer (mGal)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='densidade_referencia',
            field=models.DecimalField(decimal_places=3, default=2.67, help_text='Densidade utilizada no cálculo (padrão: 2.67 g/cm³)', max_digits=6, verbose_name='Densidade de Referência (g/cm³)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='instrumento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instrumento'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude em graus decimais', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude (graus)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Longitude em graus decimais', max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude (graus)'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='operador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='valor_gravidade',
            field=models.DecimalField(decimal_places=5, help_text='Valor da gravidade em miligals', max_digits=12, verbose_name='Valor da Gravidade (mGal)'),
        ),
    ]
