# Generated by Django 4.2.27 on 2026-01-21 23:19

import django.core.validators
from django.db import migrations, models
import medicoes.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0005_customuser_medicaogravimetrica_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaogravimetrica',
            name='croqui',
            field=models.ImageField(blank=True, help_text='Croqui ou desenho técnico da estação (máx. 5MB)', null=True, upload_to='croquis/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), medicoes.models.validar_imagem_tamanho], verbose_name='Croqui/Desenho da Estação'),
        ),
        migrations.AddField(
            model_name='medicaogravimetrica',
            name='foto_estacao',
            field=models.ImageField(blank=True, help_text='Foto da estação gravimétrica (máx. 5MB)', null=True, upload_to='estacoes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), medicoes.models.validar_imagem_tamanho], verbose_name='Foto da Estação'),
        ),
    ]
