# Generated by Django 6.0.1 on 2026-01-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0006_medicaogravimetrica_croqui_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('geosciences', 'Geociências'), ('metrology', 'Metrologia'), ('physics', 'Física'), ('defense', 'Defesa'), ('science_communication', 'Divulgação Científica')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_category',
            field=models.CharField(choices=[('academic', 'Acadêmico'), ('student', 'Estudante'), ('professional', 'Profissional')], default='professional', help_text='Categoria do usuário: acadêmico, estudante ou profissional', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='users', to='medicoes.areaofexpertise'),
        ),
    ]
