# Generated by Django 4.2.27 on 2026-01-26 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicoes', '0008_populate_expertise_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaogravimetrica',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário responsável pela medição', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
